### ISSUE TITLE
Daemon crashed! - RecursionError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by posita** [microsoft/vscode-mypy#127]
Source file: [`posita/dyce/dyce/evaluation.py`](https://github.com/posita/dyce/blob/790a067177988b2d89b4b32dcd0a5b1712c3a81b/dyce/evaluation.py)

Relevant settings:
``` json
{
  // ...
  "[python]": {
    "editor.codeActionsOnSave": {
      "source.fixAll": true,
      "source.organizeImports": true
    },
    "editor.defaultFormatter": "ms-python.black-formatter"
  },
  "isort.check": true,
  "python.defaultInterpreterPath": "/home/<username>/.virtualenvs/dyce/bin/python",
  "python.experiments.enabled": false,
  "python.linting.mypyArgs": []
}
```

<details>
<summary>Logs:</summary>

```
2023-08-27 12:43:03.583 [info] /home/<username>/.virtualenvs/dyce/bin/python -m mypy.dmypy --status-file /tmp/.vscode.dmypy_status/status-1c6d0227-f415-4160-8029-a3acd2ec57e7.json run -- --no-color-output --no-error-summary --show-absolute-path --show-column-numbers --show-error-code --no-pretty --show-error-end /home/<username>/<path>/dyce/dyce/evaluation.py
2023-08-27 12:43:03.583 [info] CWD Server: /home/<username>/<path>/dyce
2023-08-27 12:43:07.330 [info] Daemon crashed!
Traceback (most recent call last):
  File "/home/<username>/.vscode/extensions/ms-python.mypy-type-checker-2023.2.0/bundled/libs/mypy/dmypy_server.py", line 234, in serve
    resp = self.run_command(command, data)
  File "/home/<username>/.vscode/extensions/ms-python.mypy-type-checker-2023.2.0/bundled/libs/mypy/dmypy_server.py", line 281, in run_command
    ret = method(self, **data)
  File "/home/<username>/.vscode/extensions/ms-python.mypy-type-checker-2023.2.0/bundled/libs/mypy/dmypy_server.py", line 349, in cmd_run
    return self.check(sources, export_types, is_tty, terminal_width)
  File "/home/<username>/.vscode/extensions/ms-python.mypy-type-checker-2023.2.0/bundled/libs/mypy/dmypy_server.py", line 418, in check
    messages = self.fine_grained_increment_follow_imports(sources)
  File "/home/<username>/.vscode/extensions/ms-python.mypy-type-checker-2023.2.0/bundled/libs/mypy/dmypy_server.py", line 603, in fine_grained_increment_follow_imports
    messages = fine_grained_manager.update(changed, [], followed=True)
  File "/home/<username>/.vscode/extensions/ms-python.mypy-type-checker-2023.2.0/bundled/libs/mypy/server/update.py", line 267, in update
    result = self.update_one(
  File "/home/<username>/.vscode/extensions/ms-python.mypy-type-checker-2023.2.0/bundled/libs/mypy/server/update.py", line 369, in update_one
    result = self.update_module(next_id, next_path, next_id in removed_set, followed)
  File "/home/<username>/.vscode/extensions/ms-python.mypy-type-checker-2023.2.0/bundled/libs/mypy/server/update.py", line 431, in update_module
    result = update_module_isolated(
  File "/home/<username>/.vscode/extensions/ms-python.mypy-type-checker-2023.2.0/bundled/libs/mypy/server/update.py", line 618, in update_module_isolated
    load_graph(sources, manager, graph, new_modules)
  File "/home/<username>/.vscode/extensions/ms-python.mypy-type-checker-2023.2.0/bundled/libs/mypy/build.py", line 3142, in load_graph
    newst = State(
  File "/home/<username>/.vscode/extensions/ms-python.mypy-type-checker-2023.2.0/bundled/libs/mypy/build.py", line 2000, in __init__
    self.parse_file()
  File "/home/<username>/.vscode/extensions/ms-python.mypy-type-checker-2023.2.0/bundled/libs/mypy/build.py", line 2176, in parse_file
    self.tree = manager.parse_file(
  File "/home/<username>/.vscode/extensions/ms-python.mypy-type-checker-2023.2.0/bundled/libs/mypy/build.py", line 841, in parse_file
    tree = parse(source, path, id, self.errors, options=options)
  File "/home/<username>/.vscode/extensions/ms-python.mypy-type-checker-2023.2.0/bundled/libs/mypy/parse.py", line 22, in parse
    return mypy.fastparse.parse(source, fnam=fnam, module=module, errors=errors, options=options)
  File "/home/<username>/.vscode/extensions/ms-python.mypy-type-checker-2023.2.0/bundled/libs/mypy/fastparse.py", line 293, in parse
    ).visit(ast)
  File "/home/<username>/.vscode/extensions/ms-python.mypy-type-checker-2023.2.0/bundled/libs/mypy/fastparse.py", line 462, in visit
    return visitor(node)
  File "/home/<username>/.vscode/extensions/ms-python.mypy-type-checker-2023.2.0/bundled/libs/mypy/fastparse.py", line 921, in visit_Module
    body = self.fix_function_overloads(self.translate_stmt_list(mod.body, ismodule=True))
  File "/home/<username>/.vscode/extensions/ms-python.mypy-type-checker-2023.2.0/bundled/libs/mypy/fastparse.py", line 536, in translate_stmt_list
    node = self.visit(stmt)
  File "/home/<username>/.vscode/extensions/ms-python.mypy-type-checker-2023.2.0/bundled/libs/mypy/fastparse.py", line 462, in visit
    return visitor(node)
  File "/home/<username>/.vscode/extensions/ms-python.mypy-type-checker-2023.2.0/bundled/libs/mypy/fastparse.py", line 1221, in visit_Assign
    rvalue = self.visit(n.value)
  File "/home/<username>/.vscode/extensions/ms-python.mypy-type-checker-2023.2.0/bundled/libs/mypy/fastparse.py", line 462, in visit
    return visitor(node)
  File "/home/<username>/.vscode/extensions/ms-python.mypy-type-checker-2023.2.0/bundled/libs/mypy/fastparse.py", line 1494, in visit_Dict
    list(zip(self.translate_opt_expr_list(n.keys), self.translate_expr_list(n.values)))
  File "/home/<username>/.vscode/extensions/ms-python.mypy-type-checker-2023.2.0/bundled/libs/mypy/fastparse.py", line 480, in translate_expr_list
    return cast(List[Expression], self.translate_opt_expr_list(l))
  File "/home/<username>/.vscode/extensions/ms-python.mypy-type-checker-2023.2.0/bundled/libs/mypy/fastparse.py", line 475, in translate_opt_expr_list
    exp = self.visit(e)
  File "/home/<username>/.vscode/extensions/ms-python.mypy-type-checker-2023.2.0/bundled/libs/mypy/fastparse.py", line 462, in visit
    return visitor(node)
  File "/home/<username>/.vscode/extensions/ms-python.mypy-type-checker-2023.2.0/bundled/libs/mypy/fastparse.py", line 1716, in visit_List
    expr_list: list[Expression] = [self.visit(e) for e in n.elts]
  File "/home/<username>/.vscode/extensions/ms-python.mypy-type-checker-2023.2.0/bundled/libs/mypy/fastparse.py", line 1716, in <listcomp>
    expr_list: list[Expression] = [self.visit(e) for e in n.elts]
  File "/home/<username>/.vscode/extensions/ms-python.mypy-type-checker-2023.2.0/bundled/libs/mypy/fastparse.py", line 462, in visit
    return visitor(node)
  File "/home/<username>/.vscode/extensions/ms-python.mypy-type-checker-2023.2.0/bundled/libs/mypy/fastparse.py", line 1481, in visit_Lambda
    e = LambdaExpr(self.transform_args(n.args, n.lineno), self.as_required_block([body]))
  File "/home/<username>/.vscode/extensions/ms-python.mypy-type-checker-2023.2.0/bundled/libs/mypy/fastparse.py", line 651, in as_required_block
    self.translate_stmt_list(stmts, can_strip=can_strip, is_coroutine=is_coroutine)
  File "/home/<username>/.vscode/extensions/ms-python.mypy-type-checker-2023.2.0/bundled/libs/mypy/fastparse.py", line 536, in translate_stmt_list
    node = self.visit(stmt)
  File "/home/<username>/.vscode/extensions/ms-python.mypy-type-checker-2023.2.0/bundled/libs/mypy/fastparse.py", line 462, in visit
    return visitor(node)
  File "/home/<username>/.vscode/extensions/ms-python.mypy-type-checker-2023.2.0/bundled/libs/mypy/fastparse.py", line 1205, in visit_Return
    node = ReturnStmt(self.visit(n.value))
  File "/home/<username>/.vscode/extensions/ms-python.mypy-type-checker-2023.2.0/bundled/libs/mypy/fastparse.py", line 462, in visit
    return visitor(node)
  File "/home/<username>/.vscode/extensions/ms-python.mypy-type-checker-2023.2.0/bundled/libs/mypy/fastparse.py", line 1453, in visit_BinOp
    e = OpExpr(op, self.visit(n.left), self.visit(n.right))
...
  File "/home/<username>/.vscode/extensions/ms-python.mypy-type-checker-2023.2.0/bundled/libs/mypy/fastparse.py", line 462, in visit
    return visitor(node)
  File "/home/<username>/.vscode/extensions/ms-python.mypy-type-checker-2023.2.0/bundled/libs/mypy/fastparse.py", line 1453, in visit_BinOp
    e = OpExpr(op, self.visit(n.left), self.visit(n.right))
  File "/home/<username>/.vscode/extensions/ms-python.mypy-type-checker-2023.2.0/bundled/libs/mypy/fastparse.py", line 462, in visit
    return visitor(node)
  File "/home/<username>/.vscode/extensions/ms-python.mypy-type-checker-2023.2.0/bundled/libs/mypy/fastparse.py", line 1448, in visit_BinOp
    op = self.from_operator(n.op)
RecursionError: maximum recursion depth exceeded


2023-08-27 12:43:07.331 [info] file:///home/<username>/<path>/dyce/dyce/evaluation.py :
```
</details>

What is strange about the above is, if I run the command that prompts the `RecursionError` by hand in a fresh shell (no virtualenv), I get this:

```
% /home/<username>/.virtualenvs/dyce/bin/python -m mypy.dmypy --status-file /tmp/.vscode.dmypy_status/status-1c6d0227-f415-4160-8029-a3acd2ec57e7.json run -- --no-color-output --no-error-summary --show-absolute-path --show-column-numbers --show-error-code --no-pretty --show-error-end /home/<username>/<path>/dyce/dyce/evaluation.py
usage: mypy [-h] [-v] [-V] [more options; see below]
            [-m MODULE] [-p PACKAGE] [-c PROGRAM_TEXT] [files ...]
mypy: error: ambiguous option: --show-error-code could match --show-error-codes, --show-error-code-links
```

Which is a different error than I get above. If I correct for that issue (#125), I get no error:

```
% /home/<username>/.virtualenvs/dyce/bin/python -m mypy.dmypy --status-file /tmp/.vscode.dmypy_status/status-1c6d0227-f415-4160-8029-a3acd2ec57e7.json run -- --no-color-output --no-error-summary --show-absolute-path --show-column-numbers --show-error-code --no-pretty --show-error-end /home/<username>/<path>/dyce/dyce/evaluation.py
Daemon started
```

Context:

```
% uname -prism
Linux 6.4.6-76060406-generic x86_64 x86_64 x86_64
% /home/<username>/.virtualenvs/dyce/bin/python --version
Python 3.10.12
% /home/<username>/.virtualenvs/dyce/bin/python -m mypy --version
mypy 1.5.1 (compiled: yes)
% /home/<username>/.virtualenvs/dyce/bin/python -m mypy.dmypy --version
dmypy 1.5.1
```

**Comment by karthiknadig** [comment]
This seems like an issue with `dmypy`. The ` ambiguous option: --show-error-code could match --show-error-codes, --show-error-code-links` issue is fixed in pre-release. 

We plan on adding a setting to change from `dmypy` to `mypy`, since it looks like `dmypy` can cause issues in some scenarios.

**Comment by karthiknadig** [comment]
Closing in favor of https://github.com/microsoft/vscode-mypy/issues/115

**Comment by posita** [comment]
I'm not sure it's the same issue, but I will reopen if this isn't resolved after the next release or once that issue is addressed.
