### ISSUE TITLE
Can not fallback to bundled mypy with fromEnvironment

### ISSUE THREAD

**Issue by Morikko** [microsoft/vscode-mypy#184]
- Extension: `2023.4`
- Import strategy: `fromEnvironment`

When a python file is saved in an environment where mypy is not installed, there is this in the output: 

```
2023-10-23 20:32:45.177 [info] Error while checking mypy executable:
Traceback (most recent call last):
  File "/home/eric/.vscode-oss/extensions/ms-python.mypy-type-checker-2023.4.0-universal/bundled/tool/lsp_server.py", line 102, in get_mypy_info
    first_line = result.stdout.splitlines(keepends=False)[0]
IndexError: list index out of range

2023-10-23 20:32:45.177 [info] [Trace - 8:32:45 PM] Received notification 'window/logMessage'.
2023-10-23 20:32:45.177 [info] [Error - 8:32:45 PM] Linting failed with error:
Traceback (most recent call last):
  File "/home/eric/.vscode-oss/extensions/ms-python.mypy-type-checker-2023.4.0-universal/bundled/tool/lsp_server.py", line 187, in _linting_helper
    version = get_mypy_info(settings).version
AttributeError: 'NoneType' object has no attribute 'version'
```

It works again if either `mypy` is installed in the environment or if import strategy is changed to `useBundled`.

**Comment by karthiknadig** [comment]
@Morikko The initial part of the logs should have a sys.path. can you share that?

**Comment by karthiknadig** [comment]
We need to add a check if we can load `mypy` from environment. Currently we don't add the fallback, since we have to use `PYTHONPATH` to include the fallback path. If we add it before checking then python will always load the bundled mypy, even when using `fromEnvironment`.

**Comment by Morikko** [comment]
```
2023-10-23 20:33:02.025 [info] sys.path used to run Server:
   /home/eric/OneDrive/Projects
   /home/eric/.vscode-oss/extensions/ms-python.mypy-type-checker-2023.4.0-universal/bundled/libs
   /home/eric/.vscode-oss/extensions/ms-python.mypy-type-checker-2023.4.0-universal/bundled/tool
   /home/eric/.pyenv/versions/3.10.12/lib/python310.zip
   /home/eric/.pyenv/versions/3.10.12/lib/python3.10
   /home/eric/.pyenv/versions/3.10.12/lib/python3.10/lib-dynload
   /home/eric/.local/lib/python3.10/site-packages
   /home/eric/.pyenv/versions/3.10.12/lib/python3.10/site-packages
```

**Comment by adehad** [comment]
If any advice can be provided on the implementation I can give an attempt.

I think my perspective of Done would at least include:
1. Message pop-up to user if mypy was not found with reason.

**Comment by martinpakosch** [comment]
Hey guys,

just wanna add my report here.

VSCode: `1.86.2`
Extension: `2023.6.0`
Import Strategy: `fromEnvironment`
Windows 11, Python 3.11

1. When using `fromEnvironment` with a Py3.11 Environment without Mypy installed, the extension throws lots of tracebacks/errors. Fallback to bundled Mypy fails, there is no reporting/checking.
2. When using `useBundled`, the extension seems to work fine.

See both full logs of a restart. Hope this gets fixed soon... :)

[vscode-mypy-from-environment.log](https://github.com/microsoft/vscode-mypy/files/14313473/vscode-mypy-from-environment.log)
[vscode-mypy-use-bundled.log](https://github.com/microsoft/vscode-mypy/files/14313474/vscode-mypy-use-bundled.log)

Kind Regards,
Martin
